# Generated by Django 5.2.10 on 2026-02-26 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teamroleassignment",
            name="uniq_role_assignment",
        ),
        migrations.AddConstraint(
            model_name="teamroleassignment",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="uniq_role_assignment"
            ),
        ),
    ]
