# Generated by Django 5.2.10 on 2026-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityrange",
            name="eventName",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
