# Generated by Django 5.2.10 on 2026-01-31 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_team_availabilityrange_team_shift_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="join_code",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.team",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="shift",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.role",
            ),
        ),
    ]
